### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by k911** [knit-pk/api-v1-php#31]
## Changelog

- **v0.12.0**: [Milestone](https://github.com/knit-pk/api-v1-php/milestone/9)
- **v0.11.0**: [Milestone](https://github.com/knit-pk/api-v1-php/milestone/8)
- **v0.10.0**: [Milestone](https://github.com/knit-pk/api-v1-php/milestone/7)
- **v0.9.0**: [Milestone](https://github.com/knit-pk/api-v1-php/milestone/6)
- **v0.8.0**: [Milestone](https://github.com/knit-pk/api-v1-php/milestone/5)
- **v0.7.0**: [Milestone](https://github.com/knit-pk/api-v1-php/milestone/4)
- **v0.6.0**: [Milestone](https://github.com/knit-pk/api-v1-php/milestone/3)
- **v0.5.0**: [Milestone](https://github.com/knit-pk/api-v1-php/milestone/2)

## Current

**v0.13.0**:
- Milestone: https://github.com/knit-pk/api-v1-php/milestone/10

## Future

**v1.0.0**: [Milestone](https://github.com/knit-pk/api-v1-php/milestone/1)
- [x] Automatic deployment to test environment
- [x] Swagger and Data Fixtures in YAML
- [x] Automatic deployment of prebuilt container to registry
- [x] Configure code coverage
- [ ] Unit tests for internal logic
- [ ] Feature tests (for custom endpoints)
- [x] Auto tag master for release

**v1.x**:
- [ ] Unit tests for all classes
- [ ] Feature tests for REST endpoints

**Comment by k911** [comment]
Closed in favor of CHANGELOG.md
